version: "3.9"
#=======================================================================================================================#
name: mart_project
#================================================================================================================#

services:
#===============================================================================================================#
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
        - postgres_db
    ports:
      - "8000:8000" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./user-service:/code/
#=================================================================================================================#
  dapr_sidecar:
    image: daprio/daprd:latest
    container_name: dapr
    command:
      [
        "./daprd",
        "-app-id",
        "user-service",
        "-app-port",
        "8000",
        "-dapr-http-port",
        "3500",
        "-dapr-grpc-port",
        "50001",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./components:/components"
    network_mode: service:user-service
    depends_on:
      user-service:
        condition: service_healthy
    restart: on-failure
#==============================================================================================================#
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
        - POSTGRES_USER=developerhammad
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=online_mart
    ports:
        - '5433:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
#===============================================================================================================#
  pgadmin:
    image: dpage/pgadmin4:8.6
    restart: always
    container_name: PgAdmin4Cont
    ports:
      - "8010:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hammad@mart.com
      - PGADMIN_DEFAULT_PASSWORD=mart
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres_db
#==================================================================================================================#
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#=========================================================================================================================#
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:19092"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker
#==============================================================================================================================#
volumes:
  postgres_db:
    driver: local
  pgadmin:
    driver: local
#===================================================================================================================#
networks:
  default:
    driver: bridge

#===================================================================================================================#
